% Plot different plots according to slider location.
S.fh = figure('units','pixels',...
              'position',[300 300 300 350],...
              'menubar','none',...
              'name','slider_plot',...
              'numbertitle','off',...
              'resize','off');    
S.x = 0:.01:1;  % For plotting.         
S.ax = axes('unit','pix',...
            'position',[20 110 260 210]);
S.LN = plot(S.x,S.x,'r');        
S.sl_one = uicontrol('style','slide',...
                 'unit','pix',...
                 'position',[20 10 260 30],...
                 'min',1,'max',10,'val',1,...
                 'sliderstep',[1/20 1/20],...
                 'callback',{@sl_call_one,S});  
S.sl_two = uicontrol('style','slide',...
                 'unit','pix',...
                 'position',[20 50 260 30],...
                 'min',1,'max',10,'val',1,...
                 'sliderstep',[1/20 1/20],...
                 'callback',{@sl_call_two,S});  
             
function [] = sl_call_one(varargin)
    % Callback for the slider.
    [h,S] = varargin{[1,3]};  % calling handle and data structure.
    S.power = get(h,'value')
    S.x = S.x.^S.power
    set(S.LN,'ydata',S.x)
end
             
function [] = sl_call_two(varargin)
    % Callback for the slider.
    [h,S] = varargin{[1,3]};  % calling handle and data structure.
    S.oo = get(h,'value')
    S.x = S.x+S.oo
    set(S.LN,'ydata',S.x)
end